### ISSUE TITLE
Support for RankUP (maybe?)

### ISSUE THREAD

**Issue by Adam1609** [PocketEssential/PocketPerms#2]
I heard this plugin is good and I want RankUP support like
{ranks} for example, can you do that?

**Comment by xZeroMCPE** [comment]
Yeah, Don't worry.

**Comment by SinlesFlyer376** [comment]
That would be cool

**Comment by ghost** [comment]
Yea :smile:

**Comment by xZeroMCPE** [comment]
When my ... is fixed, I will completely re code PocketPerms, current code is shitty, and really messy....

**Comment by xZeroMCPE** [comment]
Completed.
