### ISSUE TITLE
Console returning errors on  Chatlistener.php

### ISSUE THREAD

**Issue by WastelandCoyote** [PocketEssential/PocketPerms#4]
Console is returning a two errors.

"[Server] INFO Warning: Invalid argument supplied for foreach() in myzip:///plugins/PocketPerms-master.zip#PocketPerms-master/src/PocketEssential/PocketPerms/PPListener/ChatListener.php on line 56"
And 
"02.04 19:31:01 [Server] INFO Notice: Undefined index: Permissions in myzip:///plugins/PocketPerms-master.zip#PocketPerms-master/src/PocketEssential/PocketPerms/PPListener/ChatListener.php on line 54"

I am running these through a plugin that can run zipped plugins, because I was having problems turning this one into a .phar, however it doesn't seem to be an issue with myzip. 

Also, I can't seem to find any information or commands as far as prefixes and colors go, is there a guide or at least the formatting layout for prefixes and/or colors? I can manually input them into the configure file for groups but I cannot seem to find the proper format.

**Comment by xZeroMCPE** [comment]
Open chat.yml and customized group format. Or add your own....


As for the error, I"ll fix it.
